# Generated by Django 4.0.3 on 2022-03-18 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_in',
            name='sent_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 13, 22, 38, 859622)),
        ),
        migrations.AlterField(
            model_name='sms_out',
            name='currentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 13, 22, 38, 861615)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='generatedTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 13, 22, 38, 861615)),
        ),
    ]
