# Generated by Django 4.0.3 on 2022-03-18 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_alter_sms_in_sent_dt_alter_sms_out_currenttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_in',
            name='sent_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 15, 9, 32, 227936)),
        ),
        migrations.AlterField(
            model_name='sms_out',
            name='currentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 15, 9, 32, 227936)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='generatedTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 15, 9, 32, 227936)),
        ),
    ]
