# Generated by Django 4.0.3 on 2022-04-06 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_sms_out_voucherid_alter_sms_in_sent_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_in',
            name='sent_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 17, 9, 16, 7497)),
        ),
        migrations.AlterField(
            model_name='sms_out',
            name='currentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 17, 9, 16, 7497)),
        ),
        migrations.AlterField(
            model_name='sms_out',
            name='voucherID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='generatedTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 17, 9, 16, 7497)),
        ),
    ]
