# Generated by Django 4.0.3 on 2022-04-07 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0007_alter_sms_in_sent_dt_alter_sms_out_currenttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_in',
            name='sent_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 15, 16, 22, 428056)),
        ),
        migrations.AlterField(
            model_name='sms_out',
            name='currentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 15, 16, 22, 428056)),
        ),
        migrations.AlterField(
            model_name='sms_out',
            name='voucherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='generatedTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 15, 16, 22, 428056)),
        ),
    ]
