# Generated by Django 4.0.3 on 2022-04-07 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0008_alter_sms_in_sent_dt_alter_sms_out_currenttime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms_out',
            old_name='sender_number',
            new_name='corresponding_request',
        ),
        migrations.RemoveField(
            model_name='sms_out',
            name='currentTime',
        ),
        migrations.RemoveField(
            model_name='sms_out',
            name='voucherAmount',
        ),
        migrations.AddField(
            model_name='sms_out',
            name='currentTime_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 15, 59, 43, 745684)),
        ),
        migrations.AlterField(
            model_name='sms_in',
            name='sent_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 15, 59, 43, 745684)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='generatedTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 15, 59, 43, 745684)),
        ),
    ]
